### ISSUE TITLE
Add support for Swift Mailer 6

### ISSUE THREAD

**Issue by ejunker** [gcrico/swift-mailer-psr-logger-plugin#1]
The `composer.json` requires `swiftmailer/swiftmailer` `~5.2`. Please add support for 6. It may not require any changes to the code other than updating the `composer.json`

**Comment by gcrico** [comment]
Tag v1.1.0 : "requires swiftmailer/swiftmailer >=5.2".
Note that  swiftmailer >= 6 requires PHP 7.
